russian_words = ['программирование', 'программист', 'профиль',
                 'язык представления', 'производительность', 'абзац',
                 'родной', 'логотип', 'список', 'блокировать', 'строка',
                 'реализация', 'значок', 'оборудование', 'плавающая запятая',
                 'объектно-ориентированный', 'ошибка', 'сборка',
                 'по умолчанию', 'значение по умолчанию', 'блочная модель',
                 'якорь', 'сообщество', 'взломанный', 'панель управления',
                 'отладка', 'отлаживать', 'разработчик', 'шифровать',
                 'возможность', 'реестр', 'перезапуск', 'маршрутизатор',
                 'маршрутизация', 'прокручивание', 'выражение',
                 'строка состояния', 'стилевое свойство', 'стилевое правило',
                 'тег', 'обновление', 'компания-разработчик', 'сайт',
                 'логический', 'щёлкнуть', 'вкладка', 'доступ',
                 'получить доступ', 'передача параметров', 'набор свойств',
                 'свойство', 'набор', 'значение', 'в этом случае',
                 'переменная', 'закрепленный', 'присоединять', 'присваивать',
                 'определять', 'чувствительный к регистру', 'как и все',
                 'подобно', 'пересылка', 'параметр', 'прокручивать', 'стиль',
                 'поддержка', 'то же самое', 'в основном', 'объяснять',
                 'беглый обзор', 'точка', 'скобка', 'допустимая переменная',
                 'строка', 'пробел', 'идентификатор', 'определенный',
                 'хранить', 'цикл', 'перечислять', 'вносить в список',
                 'переменная экземпляра', 'сравнение']

english_words = ['a programming', 'a programmer', 'a profile',
                 'a presentation language', 'a performance', 'a paragraph',
                 'native', 'a logo', 'a list', 'to lock', 'a line',
                 'an implementation', 'an icon', 'a hardware',
                 'a floating point', 'object-based', 'a bug', 'a build',
                 'by default', 'a default value', 'a box model', 'an anchor',
                 'community', 'compromised', 'a control panel', 'a debug',
                 'to debug', 'a developer', 'to encrypt', 'a feature',
                 'a registry', 'a restart', 'a router', 'a routing',
                 'a scrolling', 'a statement', 'a status bar',
                 'a style property', 'a style rule', 'a tag', 'an update',
                 'a vendor', 'a website', 'boolean', 'to click', 'а tab',
                 'an access', 'to access', 'argument passing',
                 'a collection of properties', 'a property', 'a collection',
                 'a value', 'in which case', 'a variable', 'attached',
                 'to attach', 'to assign', 'to define', 'case sensitive',
                 'like all', 'like', 'a passing', 'an argument', 'to scroll',
                 'a style', 'a support', 'same', 'basically', 'to explain',
                 'an overview', 'a dot', 'a bracket', 'a valid variable',
                 'a string', 'a space', 'an identifier', 'determined',
                 'to store', 'a loop', 'to enumerate', 'to list',
                 'an instance variable', 'a comparison']